name: 使用问题报告 / Usage Problem Report
description: 报告在使用过程中遇到的问题 / Report issues encountered while using
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写这份问题报告！在提交之前，请先搜索是否已存在类似的 issue。
        Thank you for taking the time to fill out this problem report! Before submitting, please search to see if a similar issue already exists.

  - type: checkboxes
    id: search
    attributes:
      label: 搜索现有 issues / Search existing issues
      description: 请确保没有重复的 issue。/ Please make sure there are no duplicate issues.
      options:
        - label: 我已经搜索了现有的 issues / I have searched the existing issues
          required: true

  - type: input
    id: llm-model
    attributes:
      label: 使用的 LLM 模型 / LLM Model Used
      description: 请指明您使用的是哪个 LLM 模型 / Please specify which LLM model you are using
      placeholder: 例如：GPT-3.5-turbo, BERT, etc. / For example: GPT-3.5-turbo, BERT, etc.
    validations:
      required: true

  - type: textarea
    id: problem-step
    attributes:
      label: 问题发生的步骤 / Steps Where the Problem Occurred
      description: 请详细描述在哪个步骤遇到了问题 / Please describe in detail at which step you encountered the problem
      placeholder: |
        1. 首先我... / First, I...
        2. 然后我... / Then, I...
        3. 接着出现了... / After that...
    validations:
      required: true

  - type: textarea
    id: command-screenshot
    attributes:
      label: 命令行截图 / Command Line Screenshot
      description: 请提供包含完整代码的命令行截图 / Please provide a screenshot of the command line including the full code
      placeholder: 请在此处粘贴您的截图 / Please paste your screenshot here
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: 其他信息 / Additional Information
      description: 还有什么其他相关信息可以提供吗？/ Is there any other relevant information you can provide?
      placeholder: 任何您认为可能有帮助的额外信息 / Any additional information you think might be helpful
